[package]
name = "fractal_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
# iced = "0.8.0"
iced_wgpu = "0.9.0"
iced_winit = "0.8.0"
# wgpu = "0.14.2"
# winit = "0.28.3"
